# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unique_ids.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unique_ids.proto',
  package='unique_identity',
  syntax='proto3',
  serialized_options=b'\n,jchein.name.grpc.unique_idenitity.actions.v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10unique_ids.proto\x12\x0funique_identity\"M\n\x18\x43reateOneUniqueIdRequest\x12\x31\n\nformatKind\x18\x01 \x01(\x0e\x32\x1d.unique_identity.IdFormatKind\"a\n\x1a\x43reateUniqueIdBatchRequest\x12\x31\n\nformatKind\x18\x01 \x01(\x0e\x32\x1d.unique_identity.IdFormatKind\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\rUniqueIdReply\x12\x10\n\x08uniqueId\x18\x01 \x01(\t\x12\x31\n\nformatKind\x18\x02 \x01(\x0e\x32\x1d.unique_identity.IdFormatKind*1\n\x0cIdFormatKind\x12\x08\n\x04UUID\x10\x00\x12\x08\n\x04PATH\x10\x01\x12\r\n\tURL_TOKEN\x10\x02\x32\xe5\x01\n\x19ImageUploadSigningService\x12`\n\x11\x63reateOneUniqueId\x12).unique_identity.CreateOneUniqueIdRequest\x1a\x1e.unique_identity.UniqueIdReply\"\x00\x12\x66\n\x13\x63reateUniqueIdBatch\x12+.unique_identity.CreateUniqueIdBatchRequest\x1a\x1e.unique_identity.UniqueIdReply\"\x00\x30\x01\x42.\n,jchein.name.grpc.unique_idenitity.actions.v1b\x06proto3'
)

_IDFORMATKIND = _descriptor.EnumDescriptor(
  name='IdFormatKind',
  full_name='unique_identity.IdFormatKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UUID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PATH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='URL_TOKEN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=301,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_IDFORMATKIND)

IdFormatKind = enum_type_wrapper.EnumTypeWrapper(_IDFORMATKIND)
UUID = 0
PATH = 1
URL_TOKEN = 2



_CREATEONEUNIQUEIDREQUEST = _descriptor.Descriptor(
  name='CreateOneUniqueIdRequest',
  full_name='unique_identity.CreateOneUniqueIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='formatKind', full_name='unique_identity.CreateOneUniqueIdRequest.formatKind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=114,
)


_CREATEUNIQUEIDBATCHREQUEST = _descriptor.Descriptor(
  name='CreateUniqueIdBatchRequest',
  full_name='unique_identity.CreateUniqueIdBatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='formatKind', full_name='unique_identity.CreateUniqueIdBatchRequest.formatKind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='unique_identity.CreateUniqueIdBatchRequest.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=213,
)


_UNIQUEIDREPLY = _descriptor.Descriptor(
  name='UniqueIdReply',
  full_name='unique_identity.UniqueIdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqueId', full_name='unique_identity.UniqueIdReply.uniqueId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='formatKind', full_name='unique_identity.UniqueIdReply.formatKind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=299,
)

_CREATEONEUNIQUEIDREQUEST.fields_by_name['formatKind'].enum_type = _IDFORMATKIND
_CREATEUNIQUEIDBATCHREQUEST.fields_by_name['formatKind'].enum_type = _IDFORMATKIND
_UNIQUEIDREPLY.fields_by_name['formatKind'].enum_type = _IDFORMATKIND
DESCRIPTOR.message_types_by_name['CreateOneUniqueIdRequest'] = _CREATEONEUNIQUEIDREQUEST
DESCRIPTOR.message_types_by_name['CreateUniqueIdBatchRequest'] = _CREATEUNIQUEIDBATCHREQUEST
DESCRIPTOR.message_types_by_name['UniqueIdReply'] = _UNIQUEIDREPLY
DESCRIPTOR.enum_types_by_name['IdFormatKind'] = _IDFORMATKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateOneUniqueIdRequest = _reflection.GeneratedProtocolMessageType('CreateOneUniqueIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEONEUNIQUEIDREQUEST,
  '__module__' : 'unique_ids_pb2'
  # @@protoc_insertion_point(class_scope:unique_identity.CreateOneUniqueIdRequest)
  })
_sym_db.RegisterMessage(CreateOneUniqueIdRequest)

CreateUniqueIdBatchRequest = _reflection.GeneratedProtocolMessageType('CreateUniqueIdBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUNIQUEIDBATCHREQUEST,
  '__module__' : 'unique_ids_pb2'
  # @@protoc_insertion_point(class_scope:unique_identity.CreateUniqueIdBatchRequest)
  })
_sym_db.RegisterMessage(CreateUniqueIdBatchRequest)

UniqueIdReply = _reflection.GeneratedProtocolMessageType('UniqueIdReply', (_message.Message,), {
  'DESCRIPTOR' : _UNIQUEIDREPLY,
  '__module__' : 'unique_ids_pb2'
  # @@protoc_insertion_point(class_scope:unique_identity.UniqueIdReply)
  })
_sym_db.RegisterMessage(UniqueIdReply)


DESCRIPTOR._options = None

_IMAGEUPLOADSIGNINGSERVICE = _descriptor.ServiceDescriptor(
  name='ImageUploadSigningService',
  full_name='unique_identity.ImageUploadSigningService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=353,
  serialized_end=582,
  methods=[
  _descriptor.MethodDescriptor(
    name='createOneUniqueId',
    full_name='unique_identity.ImageUploadSigningService.createOneUniqueId',
    index=0,
    containing_service=None,
    input_type=_CREATEONEUNIQUEIDREQUEST,
    output_type=_UNIQUEIDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createUniqueIdBatch',
    full_name='unique_identity.ImageUploadSigningService.createUniqueIdBatch',
    index=1,
    containing_service=None,
    input_type=_CREATEUNIQUEIDBATCHREQUEST,
    output_type=_UNIQUEIDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEUPLOADSIGNINGSERVICE)

DESCRIPTOR.services_by_name['ImageUploadSigningService'] = _IMAGEUPLOADSIGNINGSERVICE

# @@protoc_insertion_point(module_scope)
