/**
 * Type declarations for vshymanskyy/randomart
 *
 * This library generates random art through mathematical expression trees.
 * @see https://github.com/vshymanskyy/randomart
 */

import "./randomart.js"

declare module "./randomart.js" {
   /**
    * Expression tree node generated by the randomart algorithm.
    * Can be converted to a formula string via toString().
    */
   export interface ExpressionTree {
      toString(): string
   }

   /**
    * Generate a random art expression tree from a seed.
    *
    * @param seed - String seed for the random number generator
    * @returns Expression tree that can be converted to a formula
    */
   export function generate(seed: string): ExpressionTree
}
