AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    NodeCanvasLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: canvas-nodejs
            Description: canvas@2.9.1
            ContentUri: .
            CompatibleRuntimes:
                - nodejs14.x
            RetentionPolicy: Retain
            LicenseInfo: MIT
        Metadata:
            BuildMethod: makefile
          
