export const GEN_MODEL_SEED_EXTENSION_POINT_STRING = "GenModelSeed"
export type GEN_MODEL_SEED_EXTENSION_POINT =
   typeof GEN_MODEL_SEED_EXTENSION_POINT_STRING

export const GEN_MODEL_SEED_ADAPTER_ID_STRING = "GenModelSeedAdapter"
export type GEN_MODEL_SEED_ADAPTER_ID = typeof GEN_MODEL_SEED_ADAPTER_ID_STRING

export const PAINTABLE_PREFIX_SUFFIX_STRING = "PrefixSuffix"
export type PAINTABLE_PREFIX_SUFFIX = typeof PAINTABLE_PREFIX_SUFFIX_STRING

export const PAINTABLE_PHRASE_PAIR_STRING = "PhrasePair"
export type PAINTABLE_PHRASE_PAIR = typeof PAINTABLE_PHRASE_PAIR_STRING

export const PAINTABLE_SINGLE_PHRASE_STRING = "SinglePhrase"
export type PAINTABLE_SINGLE_PHRASE = typeof PAINTABLE_SINGLE_PHRASE_STRING

export const GEN_MODEL_BATCH_EXTENSION_POINT_STRING = "GenModelBatch"
export type GEN_MODEL_BATCH_EXTENSION_POINT =
   typeof GEN_MODEL_BATCH_EXTENSION_POINT_STRING

export const GEN_MODEL_BATCH_ADAPTER_ID_STRING = "GenModelBatchAdapter"
export type GEN_MODEL_BATCH_ADAPTER_ID =
   typeof GEN_MODEL_BATCH_ADAPTER_ID_STRING
