# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plot_mapping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12plot_mapping.proto\x12\x0fplot_mapping.v1\"J\n\x0eRegionBoundary\x12\x0b\n\x03top\x18\x01 \x01(\x01\x12\x0c\n\x04left\x18\x02 \x01(\x01\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x01\x12\r\n\x05right\x18\x04 \x01(\x01\"4\n\tImageSize\x12\x13\n\x0bpixelHeight\x18\x07 \x01(\r\x12\x12\n\npixelWidth\x18\x08 \x01(\r\"\xd4\x01\n\rPointPlotData\x12+\n\x08pixelRef\x18\x01 \x01(\x0e\x32\x19.plot_mapping.v1.RefPoint\x12.\n\nresolution\x18\x02 \x01(\x0b\x32\x1a.plot_mapping.v1.ImageSize\x12\x36\n\rmapped_region\x18\x03 \x01(\x0b\x32\x1f.plot_mapping.v1.RegionBoundary\x12\x0f\n\x07uniform\x18\x04 \x01(\x08\x12\x0c\n\x04rows\x18\x05 \x03(\x01\x12\x0f\n\x07\x63olumns\x18\x06 \x03(\x01\"i\n\rPointPlotMeta\x12\x0c\n\x04ulid\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\ncreateTime\x18\x03 \x01(\x04\x12(\n\x06origin\x18\x04 \x01(\x0b\x32\x18.plot_mapping.v1.BuildId\"c\n\x07\x42uildId\x12\x12\n\nsourceName\x18\x01 \x01(\t\x12\x11\n\tsourceUrl\x18\x02 \x01(\t\x12\x11\n\tsourceRef\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\r\n\x05\x62uild\x18\x05 \x01(\t\"o\n\x11PointPlotDocument\x12,\n\x04meta\x18\x01 \x01(\x0b\x32\x1e.plot_mapping.v1.PointPlotMeta\x12,\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1e.plot_mapping.v1.PointPlotData*$\n\x08RefPoint\x12\x0c\n\x08TOP_LEFT\x10\x00\x12\n\n\x06\x43\x45NTER\x10\x01\x42)\n\'name.jchein.events.grpc.plot_mapping.v1b\x06proto3')

_REFPOINT = DESCRIPTOR.enum_types_by_name['RefPoint']
RefPoint = enum_type_wrapper.EnumTypeWrapper(_REFPOINT)
TOP_LEFT = 0
CENTER = 1


_REGIONBOUNDARY = DESCRIPTOR.message_types_by_name['RegionBoundary']
_IMAGESIZE = DESCRIPTOR.message_types_by_name['ImageSize']
_POINTPLOTDATA = DESCRIPTOR.message_types_by_name['PointPlotData']
_POINTPLOTMETA = DESCRIPTOR.message_types_by_name['PointPlotMeta']
_BUILDID = DESCRIPTOR.message_types_by_name['BuildId']
_POINTPLOTDOCUMENT = DESCRIPTOR.message_types_by_name['PointPlotDocument']
RegionBoundary = _reflection.GeneratedProtocolMessageType('RegionBoundary', (_message.Message,), {
  'DESCRIPTOR' : _REGIONBOUNDARY,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.RegionBoundary)
  })
_sym_db.RegisterMessage(RegionBoundary)

ImageSize = _reflection.GeneratedProtocolMessageType('ImageSize', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESIZE,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.ImageSize)
  })
_sym_db.RegisterMessage(ImageSize)

PointPlotData = _reflection.GeneratedProtocolMessageType('PointPlotData', (_message.Message,), {
  'DESCRIPTOR' : _POINTPLOTDATA,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlotData)
  })
_sym_db.RegisterMessage(PointPlotData)

PointPlotMeta = _reflection.GeneratedProtocolMessageType('PointPlotMeta', (_message.Message,), {
  'DESCRIPTOR' : _POINTPLOTMETA,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlotMeta)
  })
_sym_db.RegisterMessage(PointPlotMeta)

BuildId = _reflection.GeneratedProtocolMessageType('BuildId', (_message.Message,), {
  'DESCRIPTOR' : _BUILDID,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.BuildId)
  })
_sym_db.RegisterMessage(BuildId)

PointPlotDocument = _reflection.GeneratedProtocolMessageType('PointPlotDocument', (_message.Message,), {
  'DESCRIPTOR' : _POINTPLOTDOCUMENT,
  '__module__' : 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlotDocument)
  })
_sym_db.RegisterMessage(PointPlotDocument)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'name.jchein.events.grpc.plot_mapping.v1'
  _REFPOINT._serialized_start=705
  _REFPOINT._serialized_end=741
  _REGIONBOUNDARY._serialized_start=39
  _REGIONBOUNDARY._serialized_end=113
  _IMAGESIZE._serialized_start=115
  _IMAGESIZE._serialized_end=167
  _POINTPLOTDATA._serialized_start=170
  _POINTPLOTDATA._serialized_end=382
  _POINTPLOTMETA._serialized_start=384
  _POINTPLOTMETA._serialized_end=489
  _BUILDID._serialized_start=491
  _BUILDID._serialized_end=590
  _POINTPLOTDOCUMENT._serialized_start=592
  _POINTPLOTDOCUMENT._serialized_end=703
# @@protoc_insertion_point(module_scope)
