# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plot_mapping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plot_mapping.proto',
  package='plot_mapping.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x12plot_mapping.proto\x12\x0fplot_mapping.v1\"j\n\x0eRegionBoundary\x12\x13\n\x0btopBoundary\x18\x01 \x01(\x01\x12\x14\n\x0cleftBoundary\x18\x02 \x01(\x01\x12\x16\n\x0e\x62ottomBoundary\x18\x03 \x01(\x01\x12\x15\n\rrightBoundary\x18\x04 \x01(\x01\"4\n\tImageSize\x12\x13\n\x0bpixelHeight\x18\x07 \x01(\r\x12\x12\n\npixelWidth\x18\x08 \x01(\r\"\x87\x01\n\tPointPlot\x12+\n\x08pixelRef\x18\x01 \x01(\x0e\x32\x19.plot_mapping.v1.RefPoint\x12\x0f\n\x07uniform\x18\x02 \x01(\x08\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0c\n\x04rows\x18\x05 \x03(\x01\x12\x0f\n\x07\x63olumns\x18\x06 \x03(\x01\"i\n\rPointPlotMeta\x12\x0c\n\x04ulid\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\ncreateTime\x18\x03 \x01(\x04\x12(\n\x06origin\x18\x04 \x01(\x0b\x32\x18.plot_mapping.v1.BuildId\"c\n\x07\x42uildId\x12\x12\n\nsourceName\x18\x01 \x01(\t\x12\x11\n\tsourceUrl\x18\x02 \x01(\t\x12\x11\n\tsourceRef\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\r\n\x05\x62uild\x18\x05 \x01(\t\"\x9e\x01\n\x11PointPlotDocument\x12,\n\x04meta\x18\x01 \x01(\x0b\x32\x1e.plot_mapping.v1.PointPlotMeta\x12/\n\x06region\x18\x02 \x01(\x0b\x32\x1f.plot_mapping.v1.RegionBoundary\x12*\n\x06points\x18\x03 \x01(\x0b\x32\x1a.plot_mapping.v1.PointPlot*$\n\x08RefPoint\x12\x0c\n\x08TOP_LEFT\x10\x00\x12\n\n\x06\x43\x45NTER\x10\x01\x42)\n\'name.jchein.events.grpc.plot_mapping.v1b\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REFPOINT = _descriptor.EnumDescriptor(
  name='RefPoint',
  full_name='plot_mapping.v1.RefPoint',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOP_LEFT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CENTER', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=708,
  serialized_end=744,
)
_sym_db.RegisterEnumDescriptor(_REFPOINT)

RefPoint = enum_type_wrapper.EnumTypeWrapper(_REFPOINT)
TOP_LEFT = 0
CENTER = 1



_REGIONBOUNDARY = _descriptor.Descriptor(
  name='RegionBoundary',
  full_name='plot_mapping.v1.RegionBoundary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topBoundary', full_name='plot_mapping.v1.RegionBoundary.topBoundary', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftBoundary', full_name='plot_mapping.v1.RegionBoundary.leftBoundary', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottomBoundary', full_name='plot_mapping.v1.RegionBoundary.bottomBoundary', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightBoundary', full_name='plot_mapping.v1.RegionBoundary.rightBoundary', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=145,
)


_IMAGESIZE = _descriptor.Descriptor(
  name='ImageSize',
  full_name='plot_mapping.v1.ImageSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixelHeight', full_name='plot_mapping.v1.ImageSize.pixelHeight', index=0,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixelWidth', full_name='plot_mapping.v1.ImageSize.pixelWidth', index=1,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=199,
)


_POINTPLOT = _descriptor.Descriptor(
  name='PointPlot',
  full_name='plot_mapping.v1.PointPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixelRef', full_name='plot_mapping.v1.PointPlot.pixelRef', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uniform', full_name='plot_mapping.v1.PointPlot.uniform', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='plot_mapping.v1.PointPlot.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='plot_mapping.v1.PointPlot.width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='plot_mapping.v1.PointPlot.rows', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='plot_mapping.v1.PointPlot.columns', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=337,
)


_POINTPLOTMETA = _descriptor.Descriptor(
  name='PointPlotMeta',
  full_name='plot_mapping.v1.PointPlotMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ulid', full_name='plot_mapping.v1.PointPlotMeta.ulid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='plot_mapping.v1.PointPlotMeta.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createTime', full_name='plot_mapping.v1.PointPlotMeta.createTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='plot_mapping.v1.PointPlotMeta.origin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=444,
)


_BUILDID = _descriptor.Descriptor(
  name='BuildId',
  full_name='plot_mapping.v1.BuildId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceName', full_name='plot_mapping.v1.BuildId.sourceName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceUrl', full_name='plot_mapping.v1.BuildId.sourceUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceRef', full_name='plot_mapping.v1.BuildId.sourceRef', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='plot_mapping.v1.BuildId.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build', full_name='plot_mapping.v1.BuildId.build', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=545,
)


_POINTPLOTDOCUMENT = _descriptor.Descriptor(
  name='PointPlotDocument',
  full_name='plot_mapping.v1.PointPlotDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='plot_mapping.v1.PointPlotDocument.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='plot_mapping.v1.PointPlotDocument.region', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='plot_mapping.v1.PointPlotDocument.points', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=706,
)

_POINTPLOT.fields_by_name['pixelRef'].enum_type = _REFPOINT
_POINTPLOTMETA.fields_by_name['origin'].message_type = _BUILDID
_POINTPLOTDOCUMENT.fields_by_name['meta'].message_type = _POINTPLOTMETA
_POINTPLOTDOCUMENT.fields_by_name['region'].message_type = _REGIONBOUNDARY
_POINTPLOTDOCUMENT.fields_by_name['points'].message_type = _POINTPLOT
DESCRIPTOR.message_types_by_name['RegionBoundary'] = _REGIONBOUNDARY
DESCRIPTOR.message_types_by_name['ImageSize'] = _IMAGESIZE
DESCRIPTOR.message_types_by_name['PointPlot'] = _POINTPLOT
DESCRIPTOR.message_types_by_name['PointPlotMeta'] = _POINTPLOTMETA
DESCRIPTOR.message_types_by_name['BuildId'] = _BUILDID
DESCRIPTOR.message_types_by_name['PointPlotDocument'] = _POINTPLOTDOCUMENT
DESCRIPTOR.enum_types_by_name['RefPoint'] = _REFPOINT

RegionBoundary = _reflection.GeneratedProtocolMessageType('RegionBoundary', (_message.Message,), dict(
  DESCRIPTOR = _REGIONBOUNDARY,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.RegionBoundary)
  ))
_sym_db.RegisterMessage(RegionBoundary)

ImageSize = _reflection.GeneratedProtocolMessageType('ImageSize', (_message.Message,), dict(
  DESCRIPTOR = _IMAGESIZE,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.ImageSize)
  ))
_sym_db.RegisterMessage(ImageSize)

PointPlot = _reflection.GeneratedProtocolMessageType('PointPlot', (_message.Message,), dict(
  DESCRIPTOR = _POINTPLOT,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlot)
  ))
_sym_db.RegisterMessage(PointPlot)

PointPlotMeta = _reflection.GeneratedProtocolMessageType('PointPlotMeta', (_message.Message,), dict(
  DESCRIPTOR = _POINTPLOTMETA,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlotMeta)
  ))
_sym_db.RegisterMessage(PointPlotMeta)

BuildId = _reflection.GeneratedProtocolMessageType('BuildId', (_message.Message,), dict(
  DESCRIPTOR = _BUILDID,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.BuildId)
  ))
_sym_db.RegisterMessage(BuildId)

PointPlotDocument = _reflection.GeneratedProtocolMessageType('PointPlotDocument', (_message.Message,), dict(
  DESCRIPTOR = _POINTPLOTDOCUMENT,
  __module__ = 'plot_mapping_pb2'
  # @@protoc_insertion_point(class_scope:plot_mapping.v1.PointPlotDocument)
  ))
_sym_db.RegisterMessage(PointPlotDocument)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'name.jchein.events.grpc.plot_mapping.v1'))
# @@protoc_insertion_point(module_scope)
