# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import signed_image_uploads_pb2 as signed__image__uploads__pb2


class ImageUploadSigningServiceStub(object):
    """Service for retrieving signed image upload URLs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createSignedUpload = channel.unary_unary(
                '/signed_image_uploads.ImageUploadSigningService/createSignedUpload',
                request_serializer=signed__image__uploads__pb2.CreateSignedUploadSingleRequest.SerializeToString,
                response_deserializer=signed__image__uploads__pb2.SignedUploadSingleReply.FromString,
                )
        self.createSignedUploadBatch = channel.unary_stream(
                '/signed_image_uploads.ImageUploadSigningService/createSignedUploadBatch',
                request_serializer=signed__image__uploads__pb2.CreateSignedUploadBatchRequest.SerializeToString,
                response_deserializer=signed__image__uploads__pb2.SignedUploadSingleReply.FromString,
                )


class ImageUploadSigningServiceServicer(object):
    """Service for retrieving signed image upload URLs
    """

    def createSignedUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createSignedUploadBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageUploadSigningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createSignedUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.createSignedUpload,
                    request_deserializer=signed__image__uploads__pb2.CreateSignedUploadSingleRequest.FromString,
                    response_serializer=signed__image__uploads__pb2.SignedUploadSingleReply.SerializeToString,
            ),
            'createSignedUploadBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.createSignedUploadBatch,
                    request_deserializer=signed__image__uploads__pb2.CreateSignedUploadBatchRequest.FromString,
                    response_serializer=signed__image__uploads__pb2.SignedUploadSingleReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signed_image_uploads.ImageUploadSigningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageUploadSigningService(object):
    """Service for retrieving signed image upload URLs
    """

    @staticmethod
    def createSignedUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signed_image_uploads.ImageUploadSigningService/createSignedUpload',
            signed__image__uploads__pb2.CreateSignedUploadSingleRequest.SerializeToString,
            signed__image__uploads__pb2.SignedUploadSingleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createSignedUploadBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/signed_image_uploads.ImageUploadSigningService/createSignedUploadBatch',
            signed__image__uploads__pb2.CreateSignedUploadBatchRequest.SerializeToString,
            signed__image__uploads__pb2.SignedUploadSingleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
